export const GET_OFFERS = "GET_OFFERS";
export const GET_OFFERS_SUCCESS = "GET_OFFERS_SUCCESS";
export const GET_OFFERS_FAILURE = "GET_OFFERS_FAILURE";

export const GET_OFFER_DETAILS = "GET_OFFER_DETAILS";
export const GET_OFFER_DETAILS_SUCCESS = "GET_OFFER_DETAILS_SUCCESS";
export const GET_OFFER_DETAILS_FAILURE = "GET_OFFER_DETAILS_FAILURE";

export const ADD_OFFER = "ADD_OFFER";
export const ADD_OFFER_SUCCESS = "ADD_OFFER_SUCCESS";
export const ADD_OFFER_FAILURE = "ADD_OFFER_FAILURE";

export const CLONE_OFFER = "CLONE_OFFER";
export const CLONE_OFFER_SUCCESS = "CLONE_OFFER_SUCCESS";
export const CLONE_OFFER_FAILURE = "CLONE_OFFER_FAILURE";

export const DELETE_OFFER = "DELETE_OFFER";
export const DELETE_OFFER_SUCCESS = "DELETE_OFFER_SUCCESS";
export const DELETE_OFFER_FAILURE = "DELETE_OFFER_FAILURE";

export const PAUSE_OFFER = "PAUSE_OFFER";
export const PAUSE_OFFER_SUCCESS = "PAUSE_OFFER_SUCCESS";
export const PAUSE_OFFER_FAILURE = "PAUSE_OFFER_FAILURE";

export const RESUME_OFFER = "RESUME_OFFER";
export const RESUME_OFFER_SUCCESS = "RESUME_OFFER_SUCCESS";
export const RESUME_OFFER_FAILURE = "RESUME_OFFER_FAILURE";

export const TOGGLE_OFFER = "TOGGLE_OFFER";
export const TOGGLE_OFFER_SUCCESS = "TOGGLE_OFFER_SUCCESS";
export const TOGGLE_OFFER_FAILURE = "TOGGLE_OFFER_FAILURE";

export const DELETE_SELECTED_OFFERS = "DELETE_SELECTED_OFFERS";
export const DELETE_SELECTED_OFFERS_SUCCESS = "DELETE_SELECTED_OFFERS_SUCCESS";
export const DELETE_SELECTED_OFFERS_FAILURE = "DELETE_SELECTED_OFFERS_FAILURE";

export const SET_OFFERS_LOADING = "SET_OFFERS_LOADING";
